### ISSUE TITLE
Plugin reports error on text against background-image with sufficient contrast

### ISSUE THREAD

**Issue by dippedrusk** [netlify-labs/netlify-plugin-a11y#67]
**Describe the bug**
I have white title text for my webpage displayed inside a jumbotron. When I set the colour of the jumbotron to be black (using `background-color: black;`) then the plugin is fine. But when I use a background-image on top of that which is also fully black, the plugin reports an error. I don't think that pa11y is actually checking the contrast of my text against the background-image.

**To Reproduce**
1. Create an element with `background-color: black` and put text in it with `color: white`
2. Then add `background-image: someimage.png` that is fully black
3. Run the plugin and you'll get an error

**Expected behavior**
I expect it not to fail in this case, or to tell me to check for this manually.

**Screenshots**
This is what the website looks like.
![Screen Shot 2021-11-24 at 12 26 27 PM](https://user-images.githubusercontent.com/15020857/143229952-96d5383f-4193-4bb5-81b6-7bcceac6f99a.png)
This is my error
![Screen Shot 2021-11-24 at 12 27 35 PM](https://user-images.githubusercontent.com/15020857/143230049-ac027c02-a406-424e-a9da-afe426792dbd.png)

**Desktop (please complete the following information):**
Not applicable

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
I'm running the plugin with Netlify, here's the public deploy log of the failing case: https://app.netlify.com/sites/naughty-wilson-684740/deploys/619e1fa9fddd7e0007db7880
Here's the public deploy when I just have `background: black;` and no `background-image`: https://app.netlify.com/sites/naughty-wilson-684740/deploys/619e229b54b5f200081e92c0

**Comment by mxmason** [comment]
Hi, @vgautam!

You're seeing this behavior from the plugin because automated testing can't confidently evaluate the color contrast of a background image. I just released `v1.0.0-alpha.5` of the plugin, which allows you to provide a new `ignoreElements` string, which you can use to explicitly _not_ test certain elements. If you are confident that your jumbotron header has good contrast, you should be able to ignore it with something like `ignoreElements = '.jumbotron > title'.

I think this gotcha with color contrast should be documented. Would you be interested in writing a new section for the README file? If not, that's okay – I'll put it on the roadmap!

**Comment by dippedrusk** [comment]
I'd love to add to the docs, that sounds really fun! I'll plan to do it this weekend if that isn't too late :)

**Comment by amykapernick** [comment]
I'm having similar issues with background gradients that affects the whole page (goes from almost black to black). The contrast is fine but I'd prefer not to ignore everything, would be great to ignore rules and just not check colour contrast to avoid those errors
